#+title:      All windows first install
#+date:       [2026-06-24 Wed 23:03]
#+filetags:   :first:install:setup:windows:
#+identifier: 20260624T230321
* scoop
** scoop help
** scoop to install list later
install scoop first

#+begin_src powershell
  iwr -useb get.scoop.sh | iex
#+end_src

add extras bucket first

#+begin_src powershell
  scoop bucket add extras nerd
#+end_src

#+begin_src powershell
  scoop install git curl  mpv musicplayer2 grep findutils xargs freetube ytdlp-interface deno ffmpeg yt-dlp VictorMono-NF album-art-downloader powertoys nomacs googlechrome-canary oh-myposh glazewm zebar emacs
#+end_src

install and enable aria2 for faster downloades
#+begin_src powershell
  scoop install aria2 && scoop config aria2-enabled true
#+end_src

* env variables
#+begin_src bash
mkdir /User/Lenovo/Vip-emacs
#+end_src

HOME = C:\Users\<username>\Vip-emacs
set home env variable to /User/Lenovo/Vip-emacs

* emacs config
** use chemacs2
clone chemacs2 to ~/.emacs.d
#+begin_src bash
 git clone https://github.com/plexus/chemacs2.git ~/.emacs.d
#+end_src
** *set the following files*
*** ~/.emacs-profiles.el

with
#+begin_src emacs-lisp
  ;; ~/.emacs-profiles.el
(("default" . ((user-emacs-directory . "~/.emacs.d-vipul"))))
#+end_src

*** ~/.emacs.d-vipul/init.el
with
#+begin_src emacs-lisp
  ;;; init.el --- Chemacs2 profile init with package.el as default

;; 1. package.el: archives and use-package
(require 'package)

(setq package-archives
      '(("melpa" . "https://melpa.org/packages/")
        ("org"   . "https://orgmode.org/elpa/")
        ("elpa"  . "https://elpa.gnu.org/packages/")))

(package-initialize)

(unless package-archive-contents
  (package-refresh-contents))

;; Ensure use-package via package.el (default package manager)
(unless (package-installed-p 'use-package)
  (package-install 'use-package))

;; 2. straight.el bootstrap (available when you explicitly want it)
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el"
                         user-emacs-directory))
      (bootstrap-version 6))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

;; 3. Org + literate config
(require 'org)

;; Keep this if you want to prevent Emacs from auto-enabling package.el packages
;; and rely on your init/config.org to control loading.
(setq package-enable-at-startup nil)

(org-babel-load-file
 (expand-file-name "config.org" user-emacs-directory))

#+end_src
*** ~/.emacs.d-vipul/config.org
[[denote:20260707T230955][emacs config chemac2]]
*** all contents
* mpv config
** mpv.conf
# General playback
save-position-on-quit=yes
resume-playback=yes
ytdl-format=bestvideo+bestaudio/best

# Better window behavior
force-window=yes
cursor-autohide=3000

# YouTube / online video handling
ytdl=yes

# Optional video quality
# ytdl-format=bestvideo[height<=1080]+bestaudio/best
** input.conf
# Vim-style controls
h seek -5
l seek 5
j add volume -5
k add volume 5
space cycle pause
q quit
G seek 100 absolute

# Optional extras
J seek -60
K seek 60
u seek -10
i seek 10

* sumatra config
* freetube json list
[[file:freetube-subscriptions-2026-07-07.db]]
* git setup
* denote setup
** nothing special
* disable start button for windows [this is not working]
Yes — in **Windows directly**, the usual built-in way is through the **Registry** or **Group Policy**, not PowerToys. For a permanent system-level disable, the simplest common method is setting `NoWinKeys=1` or using the `Scancode Map` registry entry, then restarting. [winbuzzer](https://winbuzzer.com/2024/02/09/how-to-disable-the-windows-key-in-windows-11-windows-10-xcxwbt/)

## Option 1: Registry
1. Press `Win + R`, type `regedit`, and open Registry Editor.
2. Go to `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer`.
3. If `Explorer` does not exist, create it.
4. Create a new **DWORD (32-bit)** value named `NoWinKeys`.
5. Set its value to `1`.
6. Restart your PC. [techrepublic](https://www.techrepublic.com/article/how-to-disable-the-windows-key-on-your-keyboard/)

## Option 2: Group Policy
If you have Pro/Enterprise, open `gpedit.msc`, then go to `User Configuration > Administrative Templates > Windows Components > File Explorer`, and enable **Turn off Windows Key hotkeys**. Then restart. [learn.microsoft](https://learn.microsoft.com/en-us/answers/questions/3243961/disable-windows-10-keyboard-shortcuts)

## Option 3: Scancode map
A deeper system-level method is editing `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Keyboard Layout` and adding a `Scancode Map` binary value to block the Windows keys, then rebooting. [youtube](https://www.youtube.com/watch?v=XR_RmXtjrRI)

## To undo it
- Delete `NoWinKeys`, or set it back to `0`.
- Or disable the Group Policy setting.
- Or delete `Scancode Map` and reboot. [youtube](https://www.youtube.com/watch?v=XR_RmXtjrRI)

If you want, I can give you the exact registry steps for **Windows 11 Home** or **Windows 11 Pro**.
