#+title:      thriving-2026-09-18 Fri
#+date:       [2026-09-19 Sat 13:40]
#+filetags:   :thriving:
#+identifier: 20260919T134019
#+Author: Vipul
#+SETUPFILE: ./bigblow_inline.themeg

* how to be prepared for the worst and expect the best. 
* The basic fundamentals should be clear.
* Be aware of all the tools available at your disposal, and to be able to select the best as the situation arises.
** mobile
** internet
** pc
** ai
** when to take the buddies help.
** spatial knowldge 
* Art of taking unbiased decisions in tough situations.
** knowing the basics of probability, statistics, percentage, permutations, combination, normal distribution,  and applying their principles in the real world scenarios in the back of your mind.
** understanding that some decision are reversible and some are irreversible.
** some decision are suicidal and some are hedged with no major downside.
** know when to take to take the decision on your own and when the risk of suicide is high so take second opinion or help.
** be curious - 
** always be ready to believe that what more i can know here before taking my decision?
** ask the right questions to the right people to gather the right detail in order to take the best decision.
** tails i win - heads i dont lose much.
** if you are not continously learning by being curious then your curiosity will be a nuisance.
** if your fundamentals are not clear then your questions will be wrong, which in turn will give you irrelevant answers resulting in making cloudy decisions.
** listen more than you talk.
** in tough situation you can panic or stay calm.
*** your behaviour in tough situations is derived from your life.
*** if you are continously encountering such situations then you increase your threshold to take them head on.
*** if you are not exposed to such failures/tough situations then you become overwhelmed with one.
*** when you panic you body and mind come into flight mode. 
*** in such mode the decisions made are the worst decisions.
*** because this is basic instinct to flight away as we perceive the situation as life threastening.
*** however our daily situation of such kind are barely even fatal. so the act of 
* In order to ask the right question you should have command over language and psychology.
** command over the language used for communication.
*** fluent and best use of words matter.
*** the speed and accuracy of manifesting those words in the digital world.
** knowledge of psychology to gauge the persons thought process and use the right way to gather the right detail.
*** reciprocity
*** commitment
* Richest person in the room is the one with the highest failures.
* Taking interest in long form content.
** reading books,
** podcasts
** articles.
* Reading absorbing and learning about concepts from various fields.
** machines
** business
** taxation
** eway bill
** maths - fast calculation in the mind
** hard cash counting money in a fast way
** human psychology
** technology
** finance concepts
** money concepts
** geopolitics
** human biology
** brain chemistry
** vehicle knowledge and repair knowledge.
** life skills
** genetics
** human history.
** negotiation concepts
** and many more than i cant recall.
* Being spiritual 
** in tough situation if you identify as yourself and are directly affected by it then becomes your problem and distorts your decision making.
** if you find yourself being niralamp in such situations then it helps to think critically logically in such siutaions.
** karma - believing in good karma and doing good unto others always comes back to you in your life in all forms and manner.
** best example is of climbing a mountain and climbing down.

* How do i do taks?
** make list of all tasks to make sure none get left out.
** sort them in their priority terms.
** tick each task one by one and not all together at once.
** pick the hardest and unknown first.
** delegate whatever can be delegated.
* KISS
** Keep It Simple Stupid
** any process made complicated unnecessarily gets killed eventually.
** whatever you try to do find the simplest way.
** an easy thing can be simple, but a simple thing is not always easy.
** strive to keep things simple.
* always being optimistic but also realistic at the same time.
* efficient use of resources.
** read the manuals.
** know every feature of your tools.
** think of unorthodox ways to use the tools.
** when you have a hammer, everything looks like a nail.
Functional fixedness is a cognitive bias that limits a person to use an object only in the way it is traditionally used. The concept of functional fixedness originated in Gestalt psychology, a movement in psychology that emphasizes holistic processing. Karl Duncker defined functional fixedness as being a mental block against using an object in a new way that is required to solve a problem.[1] This "block" limits the ability of an individual to use components given to them to complete a task, as they cannot move past the original purpose of those components. For example, if someone needs a paperweight, but they only have a hammer, they may not see how the hammer can be used as a paperweightf. Functional fixedness is this inability to see a hammer's use as anything other than for pounding nails; the person fails to think to use the hammer in a way other than in its conventional function.
* key concepts
** maslows hierarchies
** ppp
** 4p or marketing
** marketing
** consumer behaviour
** risk taking and when to avoid.
** confirmation bias
** anchoring bias
** framing effect
** prospect theory loss vs gain perception
** dunning kruger effect
** gamblers fallacy
** hot hand fallacy
** insensitivity to sample size
** Conservatism bias, the tendency to insufficiently revise one's belief when presented with new evidence.[3][40][41]
** planning fallacy
** Optimism bias: The tendency to be over-optimistic, underestimating greatly the probability of undesirable outcomes and overestimating favorable and pleasing outcomes (see also wishful thinking, valence effect, positive outcome bias, and compare pessimism bias).[53][54]
** Pessimism bias: The tendency to overestimate the likelihood that bad things will happen. (compare optimism bias).[56]
** Spotlight effect: The tendency to overestimate the amount that other people notice one's appearance or behavior.[57]
** Authority bias, the tendency to attribute greater accuracy to the opinion of an authority figure (unrelated to its content) and be more influenced by that opinion.[60]
** Automation bias, the tendency to depend excessively on automated systems which can lead to erroneous automated information overriding correct decisions.[61]
** Hyperbolic discounting, where discounting is the tendency for people to have a stronger preference for more immediate payoffs relative to later payoffs. Hyperbolic discounting leads to choices that are inconsistent over time—people make choices today that their future selves would prefer not to have made, despite using the same reasoning.[66] Also known as current moment bias or present bias, and related to Dynamic inconsistency. A good example of this is a study showed that when making food choices for the coming week, 74% of participants chose fruit, whereas when the food choice was for the current day, 70% chose chocolate.[67][68]
** Risk compensation or Peltzman effect: The tendency to take greater risks when perceived safety increases.[75]
** https://en.wikipedia.org/wiki/List_of_cognitive_biases
** https://en.wikipedia.org/wiki/Rigidity_(psychology) 
** https://blog.mikeriversdale.co.nz/2026/02/dunning-kruger-effect-memes-and-cartoons.html

